// Full payload dictionary — every key maps to an exact payload string.
// Keys are referenced by AuditingRuleCatalog.json behavioral rules via dataStrategyPayload field.
export const DataStrategyPayloads: Record<string, string> = {
  // ─── EMAIL ───────────────────────────────────────────────────────────────
  PAYLOAD_EMAIL_MISSING_AT: 'userdomain.com',
  PAYLOAD_EMAIL_MISSING_DOMAIN: 'user@',
  PAYLOAD_EMAIL_MISSING_USER: '@domain.com',
  PAYLOAD_EMAIL_INVALID_CHARS: 'user\\name@domain.com',
  PAYLOAD_EMAIL_LENGTH_5: 'a@b.c',
  PAYLOAD_EMAIL_LENGTH_6: 'a@b.co',
  PAYLOAD_EMAIL_LENGTH_254: 'a'.repeat(243) + '@example.com',
  PAYLOAD_EMAIL_LENGTH_255: 'a'.repeat(244) + '@example.com',
  PAYLOAD_EMAIL_MULTIPLE_AT: 'user@@test.com',
  PAYLOAD_EMAIL_DOT_START: '.user@test.com',
  PAYLOAD_EMAIL_DOT_END: 'user.@test.com',
  PAYLOAD_EMAIL_DOUBLE_DOT: 'user..name@test.com',
  PAYLOAD_EMAIL_LOCAL_EMPTY: '@test.com',
  PAYLOAD_EMAIL_LOCAL_64: 'a'.repeat(64) + '@test.com',
  PAYLOAD_EMAIL_LOCAL_65: 'a'.repeat(65) + '@test.com',
  PAYLOAD_EMAIL_VALID_DOT: 'user.name@test.com',
  PAYLOAD_EMAIL_VALID_PLUS: 'user+tag@test.com',
  PAYLOAD_EMAIL_VALID_SINGLE: 'user@test.com',
  PAYLOAD_EMAIL_DOMAIN_HYPHEN: 'user@test-domain.com',
  PAYLOAD_EMAIL_DOMAIN_SUBDOMAIN: 'user@sub.test.com',
  PAYLOAD_EMAIL_DOMAIN_NO_DOT: 'user@test',
  PAYLOAD_EMAIL_DOMAIN_TLD_SHORT: 'user@test.c',
  PAYLOAD_EMAIL_DOMAIN_HYPHEN_START: 'user@-test.com',
  PAYLOAD_EMAIL_DOMAIN_HYPHEN_END: 'user@test-.com',
  PAYLOAD_EMAIL_DOMAIN_DOUBLE_DOT: 'user@test..com',
  PAYLOAD_EMAIL_DOMAIN_LABEL_63: 'user@' + 'a'.repeat(63) + '.com',
  PAYLOAD_EMAIL_DOMAIN_LABEL_64: 'user@' + 'a'.repeat(64) + '.com',
  PAYLOAD_EMAIL_SPACE_INSIDE: 'user @test.com',
  PAYLOAD_EMAIL_SPACE_START: ' user@test.com',
  PAYLOAD_EMAIL_SPACE_END: 'user@test.com ',
  PAYLOAD_EMAIL_CONTROL_CHAR: 'user\x01@test.com',
  PAYLOAD_EMAIL_ZERO_WIDTH_SPACE: 'user\u200B@test.com',
  PAYLOAD_EMAIL_TLD_NUMERIC: 'user@test.123',
  // ─── PASSWORD ────────────────────────────────────────────────────────────
  PAYLOAD_PWD_TOO_SHORT: '1234567',
  PAYLOAD_PWD_MIN_VALID: '12345678',
  PAYLOAD_PWD_TYPICAL_VALID: 'Password1',
  PAYLOAD_PWD_EMPTY_STRING: '',
  PAYLOAD_PWD_ONLY_SPACES: '       ',
  PAYLOAD_PWD_128_CHARS: 'A'.repeat(64) + 'b'.repeat(32) + '1'.repeat(16) + '!'.repeat(16),
  PAYLOAD_PWD_129_CHARS: 'A'.repeat(64) + 'b'.repeat(32) + '1'.repeat(17) + '!'.repeat(16),
  PAYLOAD_PWD_SPECIAL_CHARS: 'P@ssw0rd!',
  PAYLOAD_PWD_ALPHANUMERIC: 'SecurePass123',
  PAYLOAD_PWD_EXTENDED_LATIN: 'Árbol$2026!',
  PAYLOAD_PWD_UNICODE: '安全Pass123!',
  PAYLOAD_PWD_INTERNAL_SPACES: 'mi clave segura',
  PAYLOAD_PWD_LEADING_SPACE: ' password123',
  PAYLOAD_PWD_TRAILING_SPACE: 'password123 ',
  PAYLOAD_PWD_ULTRA_SHORT: '123',
  PAYLOAD_PWD_LONG_COMPLEX: 'MyV3ryL0ng&Secur3P@ssw0rd!XYZ',
  PAYLOAD_PWD_NO_NUMBERS: 'PasswordQwerty',
  PAYLOAD_PWD_NO_SPECIALS: 'Password1234',
  PAYLOAD_PWD_NO_UPPERCASE: 'password1234!',
  PAYLOAD_PWD_ZERO_WIDTH_SPACE: 'pass\u200Bword123!',
  PAYLOAD_NUMBER_MULTI_DECIMAL: '1.1.1',
  PAYLOAD_NUMBER_NEGATIVE_OVERFLOW: '-9999999999999',
  // ─── TEXT ─────────────────────────────────────────────────────────────────
  PAYLOAD_TEXT_EMPTY: '',
  PAYLOAD_TEXT_ONLY_SPACES: '     ',
  PAYLOAD_TEXT_ALPHANUMERIC: 'Texto123',
  PAYLOAD_TEXT_SPECIAL_CHARS: 'texto.-_#@!',
  PAYLOAD_TEXT_EXTENDED_LATIN: 'Árbol Niño Acción',
  PAYLOAD_TEXT_UNICODE: '安全テキスト',
  PAYLOAD_TEXT_LEADING_SPACE: ' texto',
  PAYLOAD_TEXT_TRAILING_SPACE: 'texto ',
  PAYLOAD_TEXT_MULTIPLE_SPACES: 'texto  interno',
  PAYLOAD_TEXT_HTML_INJECTION: '<script>alert(1)</script>',
  PAYLOAD_TEXT_SQL_LIKE: "' OR 1=1 --",
  PAYLOAD_TEXT_CONTROL_CHAR: 'text\x01value',
  PAYLOAD_TEXT_OVERFLOW_500: 'A'.repeat(500),
  // ─── NUMBER ──────────────────────────────────────────────────────────────
  PAYLOAD_NUMBER_EMPTY: '',
  PAYLOAD_NUMBER_ALPHA: 'abc',
  PAYLOAD_NUMBER_ALPHANUMERIC: '123abc',
  PAYLOAD_NUMBER_SPECIAL_CHARS: '@#!',
  PAYLOAD_NUMBER_ZERO: '0',
  PAYLOAD_NUMBER_NEGATIVE: '-1',
  PAYLOAD_NUMBER_POSITIVE: '123',
  PAYLOAD_NUMBER_FLOAT: '10.5',
  PAYLOAD_NUMBER_LARGE_OVERFLOW: '999999999999999999999',
  PAYLOAD_NUMBER_SCIENTIFIC: '1e5',
  PAYLOAD_NUMBER_NEGATIVE_ZERO: '-0',
  PAYLOAD_NUMBER_LEADING_SPACE: ' 123',
  PAYLOAD_NUMBER_TRAILING_SPACE: '123 ',
  PAYLOAD_NUMBER_HTML_INJECTION: '<script>alert(1)</script>',
  PAYLOAD_NUMBER_SQL_LIKE: "1 OR 1=1",
  // ─── PHONE ───────────────────────────────────────────────────────────────
  PAYLOAD_PHONE_EMPTY: '',
  PAYLOAD_PHONE_ALPHA: 'abcdef',
  PAYLOAD_PHONE_ALPHANUMERIC: '123abc456',
  PAYLOAD_PHONE_SPECIAL_CHARS: '@#!',
  PAYLOAD_PHONE_DIGITS_ONLY: '5512345678',
  PAYLOAD_PHONE_TOO_SHORT: '123',
  PAYLOAD_PHONE_TOO_LONG: '12345678901234567890',
  PAYLOAD_PHONE_INTL_PREFIX: '+525512345678',
  PAYLOAD_PHONE_MULTIPLE_PLUS: '++525512345678',
  PAYLOAD_PHONE_PLUS_MIDDLE: '55+12345678',
  PAYLOAD_PHONE_DASH_SEPARATOR: '55-1234-5678',
  PAYLOAD_PHONE_SPACE_SEPARATOR: '55 1234 5678',
  PAYLOAD_PHONE_PARENTHESES: '(55)12345678',
  PAYLOAD_PHONE_EXTENSION: '5512345678 ext 123',
  PAYLOAD_PHONE_HTML_INJECTION: '<script>alert(1)</script>',
  PAYLOAD_PHONE_SQL_LIKE: "1 OR 1=1",
  PAYLOAD_PHONE_CONTROL_CHAR: '123\x01456',
  PAYLOAD_PHONE_INVALID_COUNTRY: '+00012345678',
  // ─── URL ─────────────────────────────────────────────────────────────────
  PAYLOAD_URL_EMPTY: '',
  PAYLOAD_URL_VALID_HTTP: 'http://example.com',
  PAYLOAD_URL_VALID_HTTPS: 'https://example.com',
  PAYLOAD_URL_MISSING_PROTOCOL: 'example.com',
  PAYLOAD_URL_FTP_SCHEME: 'ftp://example.com',
  PAYLOAD_URL_JAVASCRIPT_SCHEME: 'javascript:alert(1)',
  PAYLOAD_URL_DATA_URI: 'data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==',
  PAYLOAD_URL_SUBDOMAIN: 'https://sub.example.com',
  PAYLOAD_URL_MISSING_TLD: 'https://example',
  PAYLOAD_URL_DOUBLE_DOT_DOMAIN: 'https://example..com',
  PAYLOAD_URL_LABEL_63: 'https://' + 'a'.repeat(63) + '.example.com',
  PAYLOAD_URL_LABEL_64: 'https://' + 'a'.repeat(64) + '.example.com',
  PAYLOAD_URL_WITH_PORT: 'https://example.com:8080',
  PAYLOAD_URL_INVALID_PORT: 'https://example.com:99999',
  PAYLOAD_URL_WITH_PATH: 'https://example.com/path/to/resource',
  PAYLOAD_URL_WITH_QUERY: 'https://example.com?q=test&lang=es',
  PAYLOAD_URL_WITH_FRAGMENT: 'https://example.com#section',
  PAYLOAD_URL_VERY_LONG: 'https://example.com/' + 'a'.repeat(2000),
  PAYLOAD_URL_SPACES: 'https://example .com',
  PAYLOAD_URL_ENCODED_SPACE: 'https://example.com/path%20file',
  PAYLOAD_URL_HTML_INJECTION: '<script>alert(1)</script>',
  PAYLOAD_URL_CONTROL_CHAR: 'https://example.com\x01',
  PAYLOAD_URL_FILE_SCHEME: 'file:///etc/passwd',
  PAYLOAD_URL_INVALID_DOMAIN: 'https://invalid_domain',
  // ─── DATE ────────────────────────────────────────────────────────────────
  PAYLOAD_DATE_EMPTY: '',
  PAYLOAD_DATE_VALID_ISO: '2026-12-31',
  PAYLOAD_DATE_PAST: '1900-01-01',
  PAYLOAD_DATE_INVALID: '2023-13-45',
  PAYLOAD_DATE_SLASH_FORMAT: '2026/12/31',
  PAYLOAD_DATE_LOCALE_FORMAT: '31/12/2026',
  PAYLOAD_DATE_TIMESTAMP: '2026-12-31T23:59:59Z',
  PAYLOAD_DATE_ALPHANUMERIC: '2026-AB-10',
  PAYLOAD_DATE_INVALID_MONTH: '2026-13-10',
  PAYLOAD_DATE_INVALID_DAY: '2026-04-31',
  PAYLOAD_DATE_LEAP_VALID: '2028-02-29',
  PAYLOAD_DATE_LEAP_INVALID: '2027-02-29',
  PAYLOAD_DATE_ZERO: '0000-00-00',
  PAYLOAD_DATE_MIN_VALID: '1900-01-01',
  PAYLOAD_DATE_MIN_INVALID: '1899-12-31',
  PAYLOAD_DATE_MAX_VALID: '2100-12-31',
  PAYLOAD_DATE_MAX_INVALID: '2101-01-01',
  PAYLOAD_DATE_FUTURE: '2035-01-01',
  PAYLOAD_DATE_DISTANT_PAST: '2000-01-01',
  PAYLOAD_DATE_MINOR_AGE: '2012-01-01',
  PAYLOAD_DATE_EPOCH: '1970-01-01',
  PAYLOAD_DATE_YEAR_OVERFLOW: '10000-01-01',
  PAYLOAD_DATE_SQL_INJECTION: "2026-01-01' OR '1'='1",
  PAYLOAD_DATE_XSS: '<script>alert(1)</script>',
  PAYLOAD_DATE_TIMEZONE_INJECTION: '2026-01-01T00:00:00+99:99',
  // ─── CHECKBOX ────────────────────────────────────────────────────────────
  PAYLOAD_CHECKBOX_UNCHECKED: 'false',
  PAYLOAD_CHECKBOX_CHECKED: 'true',
  PAYLOAD_CHECKBOX_NULL: '',
  PAYLOAD_CHECKBOX_STRING_TRUE: '"true"',
  PAYLOAD_CHECKBOX_NUMERIC_2: '2',
  PAYLOAD_CHECKBOX_NUMERIC_1: '1',
  PAYLOAD_CHECKBOX_STRING_UPPER: 'TRUE',
  PAYLOAD_CHECKBOX_MULTIPLE: '[true,false]',
  PAYLOAD_CHECKBOX_SQL_INJECTION: "true' OR '1'='1",
  PAYLOAD_CHECKBOX_XSS: '<script>alert(1)</script>',
  // ─── RADIO ───────────────────────────────────────────────────────────────
  PAYLOAD_RADIO_INVALID_OPTION: 'INVALID_OP',
  PAYLOAD_RADIO_NULL: '',
  PAYLOAD_RADIO_VALID_OPTION: 'OPCION_A',
  PAYLOAD_RADIO_CASE_VARIATION: 'opcion_a',
  PAYLOAD_RADIO_MULTIPLE_VALUES: '["OPCION_A","OPCION_B"]',
  PAYLOAD_RADIO_DUPLICATE: '["OPCION_A","OPCION_A"]',
  PAYLOAD_RADIO_NUMERIC: '1',
  PAYLOAD_RADIO_INJECTION: 'OPCION_A<script>alert(1)</script>',
  PAYLOAD_RADIO_EMPTY_STRING: '',
  PAYLOAD_RADIO_SQL_INJECTION: "OPCION_A' OR '1'='1",
  PAYLOAD_RADIO_XSS: '<script>alert(1)</script>',
  // ─── SELECT ──────────────────────────────────────────────────────────────
  PAYLOAD_SELECT_INVALID_OPTION: 'INVALID_OPTION',
  PAYLOAD_SELECT_NULL: '',
  PAYLOAD_SELECT_VALID_OPTION: 'VALOR_A',
  PAYLOAD_SELECT_CASE_VARIATION: 'valor_a',
  PAYLOAD_SELECT_OUTDATED: 'VALOR_DESACTIVADO',
  PAYLOAD_SELECT_HIDDEN: 'VALOR_OCULTO',
  PAYLOAD_SELECT_MULTIPLE_VALID: '["VALOR_A","VALOR_B"]',
  PAYLOAD_SELECT_DUPLICATE: '["VALOR_A","VALOR_A"]',
  PAYLOAD_SELECT_NUMERIC_ID: '1',
  PAYLOAD_SELECT_OBJECT: '{"id":1,"label":"VALOR_A"}',
  PAYLOAD_SELECT_ARRAY_SINGLE: '["VALOR_A"]',
  PAYLOAD_SELECT_DEPENDENT_INVALID: 'Madrid',
  PAYLOAD_SELECT_SQL_INJECTION: "VALOR_A' OR '1'='1",
  PAYLOAD_SELECT_XSS: '<script>alert(1)</script>',
  // ─── TEXTAREA ────────────────────────────────────────────────────────────
  PAYLOAD_TEXTAREA_EMPTY: '',
  PAYLOAD_TEXTAREA_ONLY_SPACES: ' \n\n   ',
  PAYLOAD_TEXTAREA_MIN_INVALID: 'ab',
  PAYLOAD_TEXTAREA_MIN_VALID: 'a'.repeat(10),
  PAYLOAD_TEXTAREA_MAX_VALID: 'A'.repeat(5000),
  PAYLOAD_TEXTAREA_MAX_INVALID: 'A'.repeat(5001),
  PAYLOAD_TEXTAREA_SPECIAL_CHARS: 'Texto con símbolos: @#$%^&*()',
  PAYLOAD_TEXTAREA_MULTILINE: 'Línea uno\nLínea dos\nLínea tres',
  PAYLOAD_TEXTAREA_HTML_TAGS: '<b>texto</b>',
  PAYLOAD_TEXTAREA_XSS: '<script>alert(1)</script>',
  PAYLOAD_TEXTAREA_SQL_INJECTION: "' OR '1'='1",
  // ─── FILE ────────────────────────────────────────────────────────────────
  PAYLOAD_FILE_INVALID_EXT: 'INVALID_EXT',
  PAYLOAD_FILE_TOO_LARGE: 'TOO_LARGE',
  PAYLOAD_FILE_VALID_PDF: 'documento.pdf',
  PAYLOAD_FILE_DOUBLE_EXT: 'archivo.pdf.exe',
  PAYLOAD_FILE_MAX_VALID: 'FILE_5MB',
  PAYLOAD_FILE_MAX_INVALID: 'FILE_5_1MB',
  PAYLOAD_FILE_MIME_MISMATCH: 'MIME_MISMATCH',
  PAYLOAD_FILE_MALWARE_SIM: 'MALWARE_SIM',
  PAYLOAD_FILE_PATH_TRAVERSAL: '../../../etc/passwd',
  // ─── UNKNOWN ─────────────────────────────────────────────────────────────
  PAYLOAD_UNKNOWN_STRING: 'ABC123',
  PAYLOAD_UNKNOWN_NUMERIC: '12345',
  PAYLOAD_UNKNOWN_EXTREME_LENGTH: 'A'.repeat(10000),
  PAYLOAD_UNKNOWN_BINARY: '\x00\x01\x02\x03\xFF\xFE',
  PAYLOAD_UNKNOWN_SQL_INJECTION: "' OR 1=1 --",
  PAYLOAD_UNKNOWN_XSS: '<script>alert(1)</script>',
  PAYLOAD_UNKNOWN_TYPE_CONFUSION: '{"type":"object","value":1}',
  // ─── GENERIC ─────────────────────────────────────────────────────────────
  PAYLOAD_STRING_5000: 'A'.repeat(5000),
  PAYLOAD_SQL_INJECTION_BASIC: "' OR '1'='1",
  PAYLOAD_XSS_BASIC: "<script>alert('xss')</script>",
  PAYLOAD_EMPTY_STRING: ' ',
};
